- CONTRIBUTORS.txt
motivation: give credit where credit due
changes: update CONTRIBUTORS.txt with recent contributions
> update contributors list

- CONTRIBUTING.md
Correct project URL in CONTRIBUTING.md
> Correct project URL in CONTRIBUTING.md

- CODE_OF_CONDUCT.md
- scripts/soundness.sh
motivation: align with swift project coc update
changes: update coc to the version used by the swift project (contributor-covenant.org  1.4)
> update code of conduct

- docker/docker-compose.al2.55.yaml
motivation: add CI to update
changes: add docker-compose setup for 5.5
> add ci setup for 5.5

- docker/docker-compose.yaml
motivation: make it easier to shell into interactive session
changes: pass -l flag to bash to inherit PATH
> fix docker compose shell task

- docker/docker-compose.al2.58.yaml
motivation: prepare for swift 5.8
changes: add docker compose setup for nightly 5.8
> add docker compose setup for swift 5.8

- docker/docker-compose.al2.510.yaml
- docker/docker-compose.al2.59.yaml
motivaiton: test for upcoming 5.10 release
changes: add docker setup for stable 5.9 and nightly 5.10
> add 5.10 ci setup

- scripts/soundness.sh
update soundness to support 2024 and 2025 in copyright headers
> Update soundness.sh to support 2024 and 2025

- Tests/AWSLambdaRuntimeCoreTests/MockLambdaServer.swift
When testing lambda, we want to be sure that we cleanup at the end. For this reason a `withMockServer` method will come in handy.
> Add new `withMockServer` test resource method

- Plugins/AWSLambdaPackager/Plugin.swift
Fix local deps to allow local development of examples
> fix local deps in plugin

- Sources/AWSLambdaRuntimeCore/LambdaRuntime.swift
This reverts commit 2c002cc72144fe5a3f9332bb59439462472f66ad.
> Revert "Use Mutex instead of NIOLockedValueBox (#394)"

- Plugins/AWSLambdaPackager/Plugin.swift
Add verbose logging  on docker pull action when --verbose flag is on
> Increase verbosity when asked

- .github/workflows/scripts/check-archive-plugin.sh
- .github/workflows/scripts/check-link-foundation.sh
_[Explain here the context, and why you're making that change. What is the problem you're trying to solve.]_
_[Describe the modifications you've done.]_
_[After your change, what will change.]_
> [CI] add CI scripts separate from the workflows

- readme.md
Update links in the readme to point to the new doc on SPI
> add links to new documentation

- Examples/APIGateway/Package.swift
- Examples/BackgroundTasks/Package.swift
- Examples/CDK/Package.swift
- Examples/HelloWorld/Package.swift
- Examples/S3_AWSSDK/Package.swift
- Examples/S3_Soto/Package.swift
- Examples/Streaming/Package.swift
remove the platform dance on all examples.
> [examples] Simplify examples's Package.swift

- Examples/CDK/infra/package-lock.json
Just a `nom update` to remove dependabots warnings
> update CDK dependencies

- Sources/AWSLambdaRuntimeCore/Lambda+LocalServer.swift
This PR will update the 4 years old Lambda Local Server for Swift 6 concurrency.
This contributes to https://github.com/swift-server/swift-aws-lambda-runtime/issues/462
> [core] Update Local Server for Swift 6 compliance

- Sources/AWSLambdaRuntimeCore/Lambda+LocalServer.swift
fix https://github.com/swift-server/swift-aws-lambda-runtime/issues/470
> [core] LocalServer - report the error to the continuation

- readme.md
Fixed a glaring typo in the opening section.
First thing I noticed when I started reading.
Swapped two letters around.
Peace and love for all humankind.
> Quick typo fix.

- Examples/CDK/infra/package-lock.json
- Examples/CDK/infra/package.json
Update CDK dependencies to address https://github.com/swift-server/swift-aws-lambda-runtime/security/dependabot/2
> [example] Update cdk dependencies
