swift-server/swift-aws-lambda-runtime

- Sources/AWSLambdaRuntimeCore/HTTPClient.swift
Addresses #96 - This will help you stand out in a crowd of "Unknown/Unknown" in our logs
> Add a User-Agent when using the Lambda Runtime API

- Examples/LocalDebugging/MyLambda/Sources/MyLambda/main.swift
- Examples/LocalDebugging/README.md
- Sources/AWSLambdaRuntimeCore/Lambda+LocalServer.swift
- Sources/AWSLambdaRuntimeCore/Lambda.swift
motivation: make using the local debugging server easier to turn off/on without the need to change code when preparing to deploy
this came up when demoing the library to people, the idea of needing to add `#if DEBUG` on their side or repeatedly remove the `withLocalServer` was a point of push back
changes:
* add code to lambda so that in debug mode only, if the LOCAL_SERVER_ENABLED env variable is set the local degging server is started
* update example code
> add an option to start the local debugging server based on an env variable

- Sources/AWSLambdaRuntimeCore/Lambda+LocalServer.swift
motivation: better mock server
changes:
* add handler for :requestID/error
* return .accepted to lambda
* return .internalServerError to client + error json
* small refactoring of response code in mock server to make it DRYer
> handle lambda error corrctly in mock server

- docker/Dockerfile
- docker/docker-compose.al2.52.yaml
- docker/docker-compose.al2.53.yaml
motivation: swift 5.2.4 now supportes AL2
changes:
* add docker-compose file for al2 5.2.4
* correct 5.3 docker-file to say al2 instead of 18.04
> add docker-compose setup for amazon linux

- Examples/LambdaFunctions/README.md
- Examples/LambdaFunctions/scripts/deploy.sh
- Indicate bucket name must be updated before running `./scripts/deploy.sh` for example functions
> S3 bucket name must be updated before deploying

- Examples/LambdaFunctions/Sources/APIGateway/main.swift
- Examples/LambdaFunctions/Sources/Benchmark/main.swift
- Examples/LocalDebugging/README.md
- Sources/AWSLambdaEvents/Cloudwatch.swift
- Sources/AWSLambdaRuntime/Lambda+Codable.swift
- Sources/AWSLambdaRuntimeCore/Lambda+LocalServer.swift
- Sources/AWSLambdaRuntimeCore/Lambda+String.swift
- Sources/AWSLambdaRuntimeCore/LambdaHandler.swift
- Sources/AWSLambdaRuntimeCore/LambdaRunner.swift
- Sources/AWSLambdaRuntimeCore/LambdaRuntimeClient.swift
- Sources/AWSLambdaTesting/Lambda+Testing.swift
- Sources/CodableSample/main.swift
- Sources/StringSample/main.swift
- Tests/AWSLambdaEventsTests/ALBTests.swift
- Tests/AWSLambdaEventsTests/APIGateway+V2Tests.swift
- Tests/AWSLambdaEventsTests/APIGatewayTests.swift
- Tests/AWSLambdaEventsTests/CloudwatchTests.swift
- Tests/AWSLambdaEventsTests/DynamoDBTests.swift
- Tests/AWSLambdaEventsTests/S3Tests.swift
- Tests/AWSLambdaEventsTests/SNSTests.swift
- Tests/AWSLambdaEventsTests/SQSTests.swift
- Tests/AWSLambdaRuntimeCoreTests/Lambda+StringTest.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaRunnerTest.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaRuntimeClientTest.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaTest.swift
- Tests/AWSLambdaRuntimeCoreTests/Utils.swift
- Tests/AWSLambdaRuntimeTests/Lambda+CodeableTest.swift
- Tests/AWSLambdaTestingTests/Tests.swift
- readme.md
This is the continuation of my work in #112. I've moved the branch to my fork though, because of [reasons](https://twitter.com/johannesweiss/status/1268821987448836096?s=21).
As @Andrea-Scuderi has correctly [pointed out here](https://github.com/swift-server/swift-aws-lambda-runtime/issues/89#issuecomment-636500412), we should follow with our naming AWS closely. Currently the inputs name on all our handler protocols is `payload`, whereas AWS uses `event` in nearly all its languages:
- [Ruby](https://docs.aws.amazon.com/lambda/latest/dg/ruby-handler.html)
- [Node](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-handler.html)
- [Python](https://docs.aws.amazon.com/lambda/latest/dg/python-handler.html)
- [Java](https://docs.aws.amazon.com/lambda/latest/dg/java-handler.html)
- …
> Rename `payload` to `event`

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
motivation: capture issue/PR info consistently
changes: add .github directory with relevnt PR and issue templates
> add github issue and PR templates

- Sources/AWSLambdaRuntimeCore/Lambda.swift
- Sources/AWSLambdaRuntimeCore/LambdaContext.swift
- Sources/AWSLambdaRuntimeCore/LambdaRunner.swift
- Sources/AWSLambdaTesting/Lambda+Testing.swift
- Tests/AWSLambdaRuntimeCoreTests/Lambda+StringTest.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaRuntimeClientTest.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaTest.swift
- Tests/AWSLambdaRuntimeCoreTests/Utils.swift
- Tests/AWSLambdaRuntimeTests/Lambda+CodeableTest.swift
motivation: in more complext initialization scearios you may want access to a logger or other utilities
changes:
* introduce new InitializationContext type that can be extened in the future without breaking the API in semantic-major way
* instead of passing in EventLoop to the handler factory, pass in a context that includes a Logger and and EventLoop
* fix a bug where we dont hop back to the event loop when coming back from the handler
* adjust tests to the new signature
> add initialization context

- Sources/AWSLambdaRuntimeCore/LambdaContext.swift
- Sources/AWSLambdaRuntimeCore/LambdaHandler.swift
- Sources/AWSLambdaRuntimeCore/LambdaLifecycle.swift
- Sources/AWSLambdaRuntimeCore/LambdaRunner.swift
- Sources/AWSLambdaRuntimeCore/LambdaRuntimeClient.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaLifecycleTest.swift
This fixes #121.
Before we also had a small bug in the code:
```swift
public func start() -> EventLoopFuture<Void> {
assert(self.eventLoop.inEventLoop, "Start must be called on the `EventLoop` the `Lifecycle` has been initialized with.")
logger.info("lambda lifecycle starting with \(self.configuration)")
self.state = .initializing
// triggered when the Lambda has finished its last run
let finishedPromise = self.eventLoop.makePromise(of: Int.self)
finishedPromise.futureResult.always { _ in
self.markShutdown()
}.cascade(to: self.shutdownPromise)
// ^--- to cascade to the shutdown promise, the `finishedPromise` has to be fulfilled/failed
var logger = self.logger
logger[metadataKey: "lifecycleId"] = .string(self.configuration.lifecycle.id)
let runner = Runner(eventLoop: self.eventLoop, …
```
> Added `shutdown() -> EventLoopFuture<Void>` to the `ByteBufferLambdaHandler`

- Sources/AWSLambdaEvents/SES.swift
- Sources/AWSLambdaEvents/Utils/DateWrappers.swift
- Tests/AWSLambdaEventsTests/SESTests.swift
- Tests/AWSLambdaEventsTests/Utils/DateWrapperTests.swift
Add SES Lambda Event type 
Want to support Lambdas triggered by SES
- Added AWSLambdaEvents/SES.swift which include `SES.Event`
- Added `DateTimeCoding` propertyWrapper to support dates of the format "Wed, 7 Oct 2015 12:34:56 -0700".
- Added `SESTests`
You can now decode SES events.
> Added SES Event type

- Sources/AWSLambdaRuntimeCore/LambdaHandler.swift
motivation: make shutdown easier to use
changes:
* override shutdown to use the offloadQueue to perform syncShutdown
* add empty syncShutdown that can be implemented by the concrete Lambda function
> add syncShutdown to LambdaHandler

- Examples/LambdaFunctions/Dockerfile
- Examples/LambdaFunctions/scripts/build-and-package.sh
- Examples/LambdaFunctions/scripts/config.sh
- Examples/LambdaFunctions/scripts/deploy.sh
- Examples/LambdaFunctions/scripts/package.sh
- Examples/LambdaFunctions/scripts/sam-deploy.sh
- Examples/LambdaFunctions/scripts/serverless-deploy.sh
- Examples/LambdaFunctions/scripts/serverless-remove.sh
- Examples/LocalDebugging/MyLambda/Dockerfile
- Examples/LocalDebugging/MyLambda/scripts/deploy.sh
- Examples/LocalDebugging/MyLambda/scripts/package.sh
motivation: make sure examples are up tp date
changes:
* use swift:5.2 images instead of nighlies
* compute dependencies to make zipfile as small as possible
* make scripts more consistent
> examples deployment scripts refresh

- Sources/AWSLambdaEvents/Utils/DateWrappers.swift
- Tests/AWSLambdaEventsTests/Utils/DateWrapperTests.swift
- readme.md
Support decoding time zones in the following format `Fri, 26 Jun 2020 03:04:03 -0500 (CDT)`
Currently if an email is received with the common header date which includes the timezone in alphabetical form in brackets after the numeric timezone the date does not decode, and SES.Event does not decode.
Code changes include cropping text after any open bracket found in the date string before passing it through the dateFormatter. I don't know of a dataFormat string that will support the above format. If there is one obviously it would be better to use that instead. 
SES.Event decodes even when it holds a date in the above format
> SES time zone

- Examples/LocalDebugging/README.md
motivation: clearer guidelines for using the example
changes: fix a few typos, fix incorrect scheme name and add a bit more prose
> improve LocalDebugging readme

- Sources/AWSLambdaRuntimeCore/Lambda+LocalServer.swift
- Sources/AWSLambdaRuntimeCore/Utils.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaRuntimeClientTest.swift
- Tests/AWSLambdaRuntimeCoreTests/MockLambdaServer.swift
- Tests/AWSLambdaRuntimeCoreTests/UtilsTest.swift
Generate (X-Ray) Trace ID in correct format.
Generate (X-Ray) Trace ID in correct format. Helpful when testing X-Ray tracing.
- [Generating trace IDs](https://docs.aws.amazon.com/xray/latest/devguide/xray-api-sendingdata.html#xray-api-traceids)
- [Tracing header](https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html#xray-concepts-tracingheader)
- different value of [Tracing header](https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html#xray-concepts-tracingheader) generated by `LocalLambda Server` with:
- correctly formatted trace ID (root)
- removed parent segment ID (which is optional)
Example value of  `Lambda-Runtime-Trace-Id` header:
```
Root=1-5efd7f0b-da552a1eb226e4718fff8790;Sampled=1
```
before (root and parent values used to be signed integers):
``` …
```
> Generate trace ID in correct format (LocalLambda Server)

- Sources/AWSLambdaRuntime/Lambda+Codable.swift
Little common denominator after a long discussion in #129: `JSONEncoder` and `JSONDecoder` should have convenience methods to encode into `String` and decode from `String`.
- It's a little easier to deal with json payloads that are delivered in a String. (APIGateway, SNS, SQS)
- Public API is increasing
> JSONEncoder/JSONDecoder and String convenience methods

- Sources/AWSLambdaRuntimeCore/Lambda+LocalServer.swift
- Sources/AWSLambdaRuntimeCore/Lambda+String.swift
- Sources/AWSLambdaRuntimeCore/Lambda.swift
motivation: in error cases where lamnda fails to start the process fails silently and exists with code 0
changes: change the blocking API to check on the result and fatalError if lambda cannot be started / run
> give better error when lambda fails to start

- Sources/AWSLambdaRuntimeCore/Lambda+LocalServer.swift
motivation: nicer error messages
changes: return 405 when using wrong http method on the lambda invocatoin endpoint (local debug server)
> better error message when invoking local lambda server with incorrect http method

- Package.swift
- Sources/AWSLambdaEvents/Utils/DateWrappers.swift
- Tests/AWSLambdaEventsTests/Utils/DateWrapperTests.swift
motivation: simplify downstream libraries
changes: use custom ISO8601 decoders on macOS < 10.13
> remove requirment on macOS 10.13

- Sources/AWSLambdaEvents/Utils/DateWrappers.swift
motivation: use consistent date formatting across platforms
changes: use manually configured DateFormatter instead of ISO8601DateFormatter
> simplify date formatting

- docker/docker-compose.al2.53.yaml
motivation: stable 5.3 ci
changes: pin 5.3 ci jobs to 5.3 nightlies instead of master
> switch to 5.3 nightly now that it is published

- docker/docker-compose.al2.53.yaml
motivation: Swift 5.3 was released, use if for CI
changes: update docker setup to use the release version of 5.3
> Swift 5.3 was released, use if for CI

- Sources/AWSLambdaRuntimeCore/LambdaRunner.swift
Fix typo in LambdaRunner.swift documentation
> Fix typo in LambdaRunner.swift documentation

- Sources/AWSLambdaEvents/ALB.swift
- Sources/AWSLambdaEvents/APIGateway+V2.swift
- Sources/AWSLambdaEvents/APIGateway.swift
Properties of HTTPResponse types should be `var` not `let`
When creating responses in Lambda developers might want to create the response in multiple steps changing and adding properties. As of now this is not possible since all HTTPResponse types only have `let` properties. If a developer wants to mark a response as immutable they have still the option to mark the complete response as `let`.
- All properties of HTTPResponse types (`APIGateway.Response`, `APIGateway.V2.Response`, `ALB.TargetGroupResponse`) are now `var`iable
- An unsupported property has been removed from `APIGateway.V2.Response`. See [example/documentation at the very end](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html)
Developers have an easier job creating …
> Properties of HTTPResponses are now var

- Sources/AWSLambdaEvents/APIGateway+V2.swift
Made JWT in API Gateway V2 Request public.
As noted in this issue
https://github.com/swift-server/swift-aws-lambda-runtime/issues/166
the JWT instance should be public.
Added the public modifier.
The JWT instance will be available for consuming modules.
> Fixed the visibility of the JWT in an API Gateway V2 Request.

- readme.md
Ran into an issue with a proof-of-concept, and after looking through issues, realized this was just a typo in the readme.
Corrected the comment and code.
Example in readme now works correctly with SQS!
> Correct typo in SQS example

- Sources/AWSLambdaEvents/ALB.swift
Adjusted the `queryStringParameters` to be actually working with ALB.
I want my Vapor apps to work through Lambda. However, this structure does not properly represent what AWS ALB is sending to the handler. There might be use-cases in which the original implementation is working but it looks fairly untested to me and I could not find the structure, as it is now, in any examples provided by AWS.
Change `queryStringParameters` from `[String:[String]]` to `[String:String]`.
It works with the actual ALB (live example can be provided if desired) and I did not come across any need for the original implementation.
> Fixing the queryStringParameters variable for ALB

- readme.md
"avaialble" becomes "available"
Advancing the cause of Swift on Lambda, one readme fix at a time :)
"avaialble" became "available"
One less typo.
> Fixed typo.

- docker/docker-compose.al2.54.yaml
- docker/docker-compose.al2.main.yaml
- docker/docker-compose.yaml
motivation: CI for 5.4 and latest
changes: add docker setup files for 5.4 and main nightly images
> add docker setup for 5.4 and head/main

- Sources/AWSLambdaEvents/AppSync.swift
- Tests/AWSLambdaEventsTests/AppSyncTests.swift
Add support for AppSync.
AppSync is a common AWS Service, so it might be nice to support OOB support.
This is a purely additive change to support AWS AppSync. An AppSync.Request and AppSync.Response was added.
You'll be able to listen to AppSync requests as follows:
```
let myHandler = { (context: Lambda.Context, event: AppSync.Request, callback: (Result<AppSync.Response<MyCodableModel>, Error>) -> Void) in
}
```
```
let myHandler = { (context: Lambda.Context, event: AppSync.Request, callback: (Result<JSONStringResponse, Error>) -> Void) in
}
```
> Add support for AppSync events.

- Package.swift
- Sources/AWSLambdaRuntimeCore/HTTPClient.swift
- Sources/AWSLambdaRuntimeCore/LambdaConfiguration.swift
- Tests/AWSLambdaRuntimeCoreTests/MockLambdaServer.swift
- Tests/AWSLambdaRuntimeCoreTests/Utils.swift
- scripts/soundness.sh
This PR has a number of smaller perf improvements. In my measuring they account for about a 3% perf improvement with tiny string payloads. The perf improvement should be much larger for larger invocation payloads.
- Replaced `HTTPHandler` with `NIOHTTPClientResponseAggregator`, to fix a CoW issue. This will have by far the biggest speed impact. Especially for large payloads.
- Ensured that we only use one `EventLoop` in tests.
- Uses `syncOperations` to setup the `HTTPClient`.
Faster Swift Lambda Runtime.
> Small Performance Improvements

- Sources/AWSLambdaRuntime/Lambda+Codable.swift
- Sources/AWSLambdaRuntimeCore/Lambda+String.swift
- Sources/AWSLambdaRuntimeCore/LambdaHandler.swift
Add `@inlinable` to default LambdaHandler implementations. This ensures that those implementations can be inlined into user code and can be specialized for their input and output types.
We like speed.
- Add @inlinable to default protocol implementations
In my measurement I see another ~4% performance improvement.
> Inline and specialize LambdaHandlers

- docker/docker-compose.al2.54.yaml
motivation: 5.4 is out!
changes: use release docker images instead of nightly
> update 5.4 to release docker image

- SECURITY.md
- readme.md
add SECURITY.md detailing the security process
> adopt SSWG security guidelines

- Sources/AWSLambdaEvents/SNS.swift
- Tests/AWSLambdaEventsTests/SNSTests.swift
Make MessageAttributes optional on SNS.Message
When testing the following situation:
SNS Topic => SQS Queue  => Lambda
Notice that you'll see that SQS will have an SNS Message in the body without MessageAttributes
Note that after further research I also noticed that this is not sufficient:
- UnsubscribeUrl is transformed to UnsubscribeURL
- SigningCertUrl is transformed to SigningCertURL
- Updated the unit tests
- Made MessageAttributes optional
MessageAttributes will be optional, and you'll be able to parse an SNS Message in the situation described in the motivation
> SNS MessageAttributes are optional

- Package.swift
- Sources/AWSLambdaRuntimeCore/LambdaHandler.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaHandlerTest.swift
- For the 0.5.0 release we need to support the real platform requirements
- Replace the wildcard platform requirements with `@available(macOS 12, iOS 15, tvOS 15, watchOS 8, *)` 
- Updated the dependencies: `swift-nio`, `swift-log` and `swift-backtrace`
- Ready for `0.5.0`
> Fixes platform requirements

- Sources/AWSLambdaRuntimeCore/LambdaContext.swift
- Sources/AWSLambdaRuntimeCore/LambdaRunner.swift
_Lambda.Context changed from a class to a struct._
As described in issue #215. Lambda.Context is currently a class that is a wrapper around values. Because it should be a value type, it was changed from a class to a struct.
The modifications are nearly identical to the changes from #167 - minus the addition of Baggage. The change from a class to a struct also follows CoW semantics to keep performance high. Line 104 of Sources/AWSLambdaRuntimeCore/LambdaRunner.swift had "convenience" and "file private" removed as well.
There are two differences between #167 and this modification: 1) At the time of forking, Tests/AWSLambdaRuntimeTests/Lambda+CodeableTest.swift was not present. 2) There is no Baggage
Lambda.Context is now a CoW-boxed struct instead of a class.
_This is my first contribution. …
> Change Lambda.Context from class to struct

- Package.swift
- Sources/AWSLambdaRuntimeCore/LambdaHandler.swift
Motivation:
AWSLambdaRuntimeCore and MockServer both have dependencies on the NIO
module, but they don't express this in their Package.swift: they
implicitly rely on these dependencies being met by the NIOHTTP1 import.
This was always brittle: it could lead to timing issues in the build
that could lead to it failing.
Modifications:
- Correctly express the dependency on NIO in Package.swift
- Correctly import _NIOConcurrency in files where it's used
Result:
Better and more accurate builds.
> Clean up dependency graph and imports

- Package.swift
- Sources/AWSLambdaRuntimeCore/LambdaHandler.swift
In swift-nio completeWithAsync was renamed to completeWithTask
https://github.com/apple/swift-nio/commit/e66b64e4e3e3409729befb31d894b89062e003dc
completeWithAsync causes build errors on macOS 12 and Xcode 13
Renamed completeWithAsync to completeWithTask
No more build errors
> Renamed completeWithAsync to completeWithTask

- Examples/LambdaFunctions/Sources/Benchmark/main.swift
- Sources/AWSLambdaRuntimeCore/LambdaHandler.swift
- Sources/AWSLambdaRuntimeCore/LambdaRunner.swift
- Sources/AWSLambdaTesting/Lambda+Testing.swift
- Sources/CodableSample/main.swift
- Sources/StringSample/main.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaHandlerTest.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaHandlers.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaLifecycleTest.swift
- Tests/AWSLambdaRuntimeTests/Lambda+CodeableTest.swift
Fixes #89, for `ByteBufferLambdaHandler` and `EventLoopLambdaHandler` protocol.
In the new `LambdaHandler` protocol, the `event` already is in front of the `context`. Let's do the same for `ByteBufferLambdaHandler` and `EventLoopLambdaHandler`.
> Reorder Event and Context.

- Examples/LambdaFunctions/Sources/Benchmark/main.swift
- Examples/LambdaFunctions/Sources/CurrencyExchange/CurrencyExchangeHandler.swift
- Examples/LambdaFunctions/Sources/ErrorHandling/ErrorsHappenHandler.swift
- Examples/LambdaFunctions/Sources/HelloWorld/HelloWorldHandler.swift
- Examples/LocalDebugging/MyLambda/Sources/MyLambda/MyLambdaHandler.swift
- Sources/AWSLambdaRuntime/Lambda+Codable.swift
- Sources/AWSLambdaRuntimeCore/Lambda+String.swift
- Sources/AWSLambdaRuntimeCore/LambdaHandler.swift
- Sources/AWSLambdaRuntimeCore/LambdaRunner.swift
- Sources/AWSLambdaTesting/Lambda+Testing.swift
- Sources/CodableSample/main.swift
- Sources/StringSample/main.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaHandlerTest.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaHandlers.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaLifecycleTest.swift
- Tests/AWSLambdaRuntimeTests/Lambda+CodeableTest.swift
- Tests/AWSLambdaTestingTests/Tests.swift
Drop event label from handle methods in LambdaHandlers protocols
In Lambda functions user's handle events from different sources. Those events can be `S3Event`s, but also `APIGatewayRequest`s. Let's look at a Lambda, that integrates with APIGateway.
```swift
@main
struct EchoLambda: AsyncLambdaHandler {
typealias Event = APIGatewayV2Request
typealias Output = APIGatewayV2Response
init(context: Lambda.InitializationContext) async throws {}
func handle(event: APIGatewayV2Request, context: Lambda.Context) async throws -> APIGatewayV2Response {
APIGatewayV2Response(statusCode: .ok, body: event.body)
}
}
```
The argument in the `handle` method is labeled `event` even though, in this case `request` would be clearly a better name. The user could use `request` as a parameter name by explicitly …
> [RFC] Drop event label from handle methods in LambdaHandlers

- docker/docker-compose.al2.55.yaml
motivation: 5.5 release is available
changes: update docker CI setup to use the release version of 5.5
> Use release version of 5.5 in CI

- Package.swift
- Sources/AWSLambdaRuntimeCore/Lambda.swift
- Sources/AWSLambdaRuntimeCore/LambdaHandler.swift
- Sources/AWSLambdaTesting/Lambda+Testing.swift
SwiftNIO 2.33.0 was just released. The `_NIOConcurrency` is now empty, since its functionality was moved to NIOCore. Remove the non API stable dependency.
> Remove dependency on _NIOConcurrency

- Sources/AWSLambdaRuntimeCore/LambdaHandler.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaHandlerTest.swift
Add extra code guards so that Xcode 13 will compile this package on macOS 11, which does not have symbols for Concurrency yet.
Allow compilation with Xcode 13
Changed code guards `#if compiler(>=5.5)` to `#if compiler(>=5.5) && canImport(_Concurrency)`
Got the idea from swift-server/swift-service-lifecycle#110
Successfully compiles with Xcode 13
> Add guards for code that relies on _Concurrency to allow compilation with Xcode 13

- NOTICE.txt
- Sources/AWSLambdaRuntimeCore/LambdaRequestID.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaRequestIDTests.swift
If we want to minimize allocations for every invocation, we need to look at types that currently allocate. Currently we use a String to hold the request id. However since the request id is a uuid, that string is 36 characters long. This is way above the 15 character string allocation threshold. The go to type in this case would be `UUID`. However `UUID` is in Foundation and we want to keep the lambda runtime Foundation free.
This pr introduces a LambdaRequestID to represent a uuid. One nice side effect of having our own uuid case is: We can make writing the uuid-string to a ByteBuffer allocation free (since no intermediate translation to a string is needed first).
This pr does not add any public API.
> Add LambdaRequestID

- Sources/AWSLambdaRuntimeCore/ControlPlaneRequestEncoder.swift
- Tests/AWSLambdaRuntimeCoreTests/ControlPlaneRequestEncoderTests.swift
Add a new `ControlPlaneRequestEncoder` that encodes all requests into an existing buffer. 
We want to write our request to the ControlPlaneAPI into one buffer, that we can reuse over and over. 
- Add `ControlPlaneRequestEncoder` that writes `ControlPlaneRequest`s into a buffer that is reused.
- Fewer messages on the ChannelPipeline.
> Add ControlPlaneRequestEncoder

- Examples/Benchmark/BenchmarkHandler.swift
- Examples/Deployment/Sources/Benchmark/BenchmarkHandler.swift
- Sources/AWSLambdaRuntimeCore/Lambda.swift
- Sources/AWSLambdaRuntimeCore/LambdaContext.swift
- Sources/AWSLambdaRuntimeCore/LambdaHandler.swift
- Sources/AWSLambdaRuntimeCore/LambdaRunner.swift
- Sources/AWSLambdaRuntimeCore/LambdaRuntime.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaHandlerTest.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaHandlers.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaRunnerTest.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaRuntimeClientTest.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaRuntimeTest.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaTest.swift
- Tests/AWSLambdaRuntimeCoreTests/Utils.swift
- Tests/AWSLambdaRuntimeTests/Lambda+CodableTest.swift
As previously discussed...
We want to use the same lambda application lifecycle for all lambda implementations. Currently we support `@main` only for the `LambdaHandler` protocol. This PR brings the `@main` functionality to the lower level protocols.
- Add a factory method requirement to the `ByteBufferLambdaHandler` protocol
- Remove the factory callback (`HandlerFactory`) from the `LambdaRuntime` and `Lambda`
- Make the `LambdaRuntime` generic over the `LambdaHandler` type
- Adjust tests
- Write better docu
- The application lifecycle is the same for all protocol levels.
> Lambda factory as a protocol requirement.

- Sources/AWSLambdaRuntimeCore/ControlPlaneRequest.swift
- Tests/AWSLambdaRuntimeCoreTests/ControlPlaneRequestTests.swift
- scripts/soundness.sh
Adds a default value for the Lambda-Runtime-Trace-Id header, to make it compatible with the AWS SAM CLI and other applications depending on the Lambda Runtime Interface Emulator. 
Currently the Swift Runtime is incompatible with the Lambda Runtime Interface Emulator.
Adds a default value for the Lambda-Runtime-Trace-Id header.
This is similar to what the [Rust runtime](https://github.com/awslabs/aws-lambda-rust-runtime/blob/f33fa059a88869b38646d875688fab58885208de/lambda-runtime/src/types.rs#L157) is doing.
The Swift Runtime will be compatible with the Lambda Runtime Interface Emulator.
> Add default value for traceID header

- docker/docker-compose.al2.56.yaml
- docker/docker-compose.al2.57.yaml
motivation: 5.6 is out
changes:
* use release version of 5.6
* add docker setup for 5.7 (using nightly for now)
> 0.x ci update

- Sources/AWSLambdaRuntimeCore/LambdaContext.swift
- Sources/AWSLambdaRuntimeCore/LambdaHandler.swift
- Sources/AWSLambdaRuntimeCore/LambdaRunner.swift
- Sources/AWSLambdaRuntimeCore/LambdaRuntime.swift
- Sources/AWSLambdaRuntimeCore/Terminator.swift
- Sources/AWSLambdaTesting/Lambda+Testing.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaRuntimeTest.swift
- Tests/AWSLambdaRuntimeCoreTests/Utils.swift
- Tests/AWSLambdaRuntimeTests/Lambda+CodableTest.swift
motivation: make it simpler to register shutdown hooks
changes:
* introduce Terminator helper that allow registering and de-registaring shutdown handlers
* expose the new terminator handler on the InitializationContext and deprecate ShutdownContext
* deprecate the Handler::shutdown protocol requirement
* update the runtime code to use the new terminator instead of calling shutdown on the handler
* add and adjust tests
> terminator handler

- Sources/AWSLambdaRuntimeCore/LambdaContext.swift
- Sources/AWSLambdaRuntimeCore/LambdaHandler.swift
- Sources/AWSLambdaRuntimeCore/LambdaRuntime.swift
- Sources/AWSLambdaRuntimeCore/LambdaRuntimeClient.swift
- Sources/AWSLambdaRuntimeCore/Sendable.swift
- Sources/AWSLambdaRuntimeCore/Terminator.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaTest.swift
- docker/Dockerfile
motivation: adopt to sendable requirments in swift 5.6
changes:
* define sendable shims for protocols and structs that may be used in async context
* adjust tests
* add a test to make sure no warning are emittted
> adoption of sendable

- Sources/AWSLambdaRuntime/Lambda+Codable.swift
motivation: we should not publicly extend types we do not own
change: remove extensions which are largely API sugar that is not directly related to Lambda
> remove extension for JSONEncoder and JSONDecoder

- Examples/Benchmark/BenchmarkHandler.swift
- Examples/Deployment/Sources/Benchmark/BenchmarkHandler.swift
- Examples/Deployment/Sources/HelloWorld/HelloWorldHandler.swift
- Examples/Echo/Lambda.swift
- Examples/ErrorHandling/Lambda.swift
- Examples/Foundation/Lambda.swift
- Examples/JSON/Lambda.swift
- Examples/LocalDebugging/MyLambda/Lambda.swift
- Examples/Testing/Sources/Lambda.swift
- Sources/AWSLambdaRuntimeCore/ControlPlaneRequest.swift
- Sources/AWSLambdaRuntimeCore/HTTPClient.swift
- Sources/AWSLambdaRuntimeCore/Lambda+LocalServer.swift
- Sources/AWSLambdaRuntimeCore/Lambda.swift
- Sources/AWSLambdaRuntimeCore/LambdaConfiguration.swift
- Sources/AWSLambdaRuntimeCore/LambdaContext.swift
- Sources/AWSLambdaRuntimeCore/LambdaHandler.swift
- Sources/AWSLambdaRuntimeCore/LambdaRunner.swift
- Sources/AWSLambdaRuntimeCore/LambdaRuntime.swift
- Sources/AWSLambdaRuntimeCore/LambdaRuntimeClient.swift
- Sources/AWSLambdaTesting/Lambda+Testing.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaHandlerTest.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaHandlers.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaRuntimeClientTest.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaRuntimeTest.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaTest.swift
- Tests/AWSLambdaRuntimeCoreTests/Utils.swift
- Tests/AWSLambdaRuntimeTests/Lambda+CodableTest.swift
- Tests/AWSLambdaTestingTests/Tests.swift
motivation: consisten naming convention
changes:
* Lambda.InitializationContext -> LambdaInitializationContext
* Lambda.Runner -> LambdaRunner
* Lambda.Configuration -> LambdaConfiguration
* Lambda.RuntimeError -> LambdaRuntimeError
* adjust call sites, tests, and examples
> prefix data structures with Lambda instead of namespacing them

- scripts/check_no_api_breakages.sh
We should check for API breaking changes in CI, to ensure we don't accidentally break API going forwards.
- We should check for API breaking changes in CI, to ensure we don't accidentally break API going forwards.
- Add a script that checks for breaking changes (copy and pasted from NIO).
- We ensure we don't accidentally break API after 1.0
@tomerd we need to add another CI that runs the API checking script.
> Add script to check for API breaks

- Examples/Deployment/README.md
This adds brief notes on building from an M1 as I don't believe the samples will work without special adjustments.
I had spent a few days attempting to build from my M1 but was a bit confused as to what was wrong. It turned out to be a very simple fix. 
Update the Deployment documentation so that M1 users quickly know they need to make some adjustments before spending time trying to deploy the samples.
Hopefully more users on M1s will be able to deploy the samples.
> Add special Deployment instructions for the Mac M1

- Sources/AWSLambdaRuntimeCore/LambdaRunner.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaTest.swift
- docker/docker-compose.yaml
motivation: cleanup incorrect concurent code in test
changes: use .get instead of .wait
> fix concurrency api usage

- readme.md
This change adds a note about naming the file `main.swift` and using the `@main` attribute.
When transitioning to the 1.x API users may have had their files named `main.swift` and will encounter the error `'main' attribute cannot be used in a module that contains top-level code`. This change adds a note to help remedy this issue and make it easy to locate when searching the repository.
- Added note to `readme.md`
- Improved documentation.
> Add note about naming the file main.swift to README

- readme.md
Changed the `SQS.Event` type to the existing `SQSEvent` type
Try to run the mentioned code snippet throws a *non existing type* error.
Because the AWS events are developed in a separated package could takes some times to find the error to a developer trying to use this snippet as base for his/her code.
Also, the `Void` returning type has been removed from code, following the [Apple style guideline](https://developer.apple.com/documentation/swift/void) related to the use of `Void`.
At **README.MD** file, change the snippet to use the right type and `Void` returning type removed to follow the Apple style guideline.
The snippet 
```swift
// Import the modules
import AWSLambdaRuntime
import AWSLambdaEvents
@main
struct MyLambda: SimpleLambdaHandler {
// In this example we are receiving a SQS …
```
> README.MD SimpleLambdaHandler example with events.

- readme.md
Provide information related to the arguments that the new `archive` command can take.
The **README.MD** file only mention the new `archive` command, but doesn't mention the arguments that this command can take.
Some of them are really useful, like the `--output-path` or `--swift-version` parameters, and it could be helpful for developers known the different arguments that this plugin provides.
Added new content to the **Deploying to AWS Lambda** section.
There's a new list with the `archive` command arguments and an example of usage.
English is not my mother language (🇪🇸😜) and probably text style could be changed to a more appropriate style. Feel free to let corrections as comments over this PR. 
Thanks 😀
> Archive plugin documentation

- Examples/Benchmark/Package.swift
- Examples/Deployment/Package.swift
- Examples/Echo/Package.swift
- Examples/ErrorHandling/Package.swift
- Examples/Foundation/Package.swift
- Examples/JSON/Package.swift
- Examples/LocalDebugging/MyLambda/Package.swift
- Examples/Testing/Package.swift
- docker/docker-compose.al2.57.yaml
- docker/docker-compose.al2.58.yaml
- docker/docker-compose.al2.main.yaml
- docker/docker-compose.yaml
motivation: examples can be confusing since they use relative path to the library for CI purposes
changes:
* update examples to use the library URL, expect when env variable is set for CI purposes
* rename docker compose job to test-examples since it is more accurate
> improve examples

- readme.md
Fix the readme link's domain
I want the link to work
Added the letter `v`
The link works 🎉
> Fix a dead tutorial link

- Package@swift-5.7.swift
- Package@swift-5.8.swift
- Sources/AWSLambdaRuntimeCore/Lambda.swift
motivation: swift 5.9 ships with builtin backtrace support \o/
changes:
* remove the dependency on swift-backtrace when using swift 5.9 or above
* conditionalize the call to Backtrace.install to relevant versions only
> remove swift-backtrace in swift >= 5.9

- scripts/soundness.sh
Ignore swift files part of docc
Fix for issue https://github.com/swift-server/swift-aws-lambda-runtime/issues/306
`scripts/soundness.sh` ignores `.swift` files in the `Documentation.docc` directories.
Swift code snippets that are part of the `Documentation.docc` directory are not required to have a license header.
> ignore swift files part of docc

- Sources/AWSLambdaRuntimeCore/LambdaContext.swift
motivation: address warnings
changes: remove pre-concurrency flag when not longer needed
> remove redundant pre-concurrency flag

- Sources/AWSLambdaRuntimeCore/Lambda.swift
- Sources/AWSLambdaRuntimeCore/LambdaHandler.swift
- Sources/AWSLambdaRuntimeCore/LambdaRunner.swift
- Sources/AWSLambdaRuntimeCore/LambdaRuntime.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaRunnerTest.swift
- Tests/AWSLambdaRuntimeCoreTests/Utils.swift
Motivation:  Provide the flexibility for custom initialization of the HandlerType as this will often be required by higher level frameworks.
Modifications:
* Modify the LambdaRuntime type to accept a closure to provide the handler rather than requiring that it is provided by a static method on the Handler type
* Update downstream code to use HandlerProvider
* Update upstream code to support passing Hanlder Type of Handler Provider
* Add and update tests
Originally suggested and coded by @tachyonics in https://github.com/swift-server/swift-aws-lambda-runtime/pull/308
> allow custom initialization of the HandlerType of the LambdaRuntime

- Sources/AWSLambdaRuntimeCore/LambdaRunner.swift
- readme.md
This PR adds a `logger.trace()` in `LambdaRuntime` just before calling user's handler. 
It allows to see in the trace logs a string representation of the event passed by the AWS Service.
When there is no or poor documentation of the event passed to a lambda function, is it super hard to figure out the exact `Codable` struct to implement for the `LambdaHandler`.
With other programming languages, such as Python or Typescript, developers typically add a `print(event)` or `console.log(event)` at the start of the lambda handler function to figure out the exact type of data to deal with.
When using the Swift AWS Lambda Runtime, it's not possible because the bytes received are encoded to a `struct` before the user's code is called.
When there is a mismatch between the received bytes and the …
> Add tracing of request events + mention LOG_LEVEL in README

- Sources/AWSLambdaRuntimeCore/Lambda.swift
Allow the changing of the local lambda server's invocation endpoint
_[Explain here the context, and why you're making that change. What is the problem you're trying to solve.]_
As described in https://github.com/swift-server/swift-aws-lambda-runtime/issues/320 I want to be able to use other tooling that expects the local invocation endpoint to have a specific path, not just `/invoke`.
I have added an envionrment variable option that lets you override the invocation endpoint url.
If you set LOCAL_LAMBDA_SERVER_ENABLED to run locally, you can now also set LOCAL_LAMBDA_SERVER_INVOCATION_ENDPOINT to any value to change the path, e.g. to `/2015-03-31/functions/function/invocations` to match how the "[runtime interface emulator](https://docs.aws.amazon.com/lambda/latest/dg/images-test.html)" …
> Local lambda invocation endpoint env var

- Plugins/AWSLambdaPackager/Plugin.swift
Use the newly introduced `LAMBDA_USE_LOCAL_DEPS` environment variable inside Docker to allow to build Swift Lambda function using the local copy of the runtime 
When developing and testing ideas on the Swift AWS Lambda Runtime, we often need to build code for deployment.
The local and CI build systems have been modified to allow to reference the local filesystem version of the library, instead of the remote one on Git. It uses the `LAMBDA_USE_LOCAL_DEPS` to make the difference. The examples' `Package.swift` have been updated by https://github.com/swift-server/swift-aws-lambda-runtime/pull/292 
This PR, adds a check in the archiver plugin to mount `../..` in the docker container rather than `.` when building with local dependencies. This allows to refer to the local copy of the Swift AWS …
> [plugin] Use LAMBDA_USE_LOCAL_DEPS env var in local builds with docker

- readme.md
Update the README to reflect last PR merge 
https://github.com/swift-server/swift-aws-lambda-runtime/pull/321
> add LOCAL_LAMBDA_SERVER_INVOCATION_ENDPOINT to the readme

- Plugins/AWSLambdaPackager/Plugin.swift
Fixes #327 
The package still doesn't fully compile but the next error is upstream in swift-nio:
```
PS C:\Users\sven_\Projects\swift-aws-lambda-runtime> swift build
C:\Users\sven_\Projects\swift-aws-lambda-runtime\Plugins\AWSLambdaPackager\Plugin.swift:213:13: warning: code after 'throw' will never be executed
try self.execute(
^
C:\Users\sven_\Projects\swift-aws-lambda-runtime\.build\checkouts\swift-docc-plugin\Plugins\Swift-DocC Convert\Symbolic Links\SharedPackagePluginExtensions\PackageExtensions.swift:31:17: warning: switch covers known cases, but 'TargetDependency' may have additional unknown values
switch dependency {
^
C:\Users\sven_\Projects\swift-aws-lambda-runtime\.build\checkouts\swift-docc-plugin\Plugins\Swift-DocC Convert\Symbolic …
```
> Fix compile error on Windows

- Package.swift
- Plugins/AWSLambdaPackager/Plugin.swift
- Sources/AWSLambdaRuntimeCore/Lambda.swift
> Allow to compile with the Linux Static SDK (aka musl)

- Examples/ResourcePackaging/Lambda.swift
- Examples/ResourcePackaging/Package.swift
- Examples/ResourcePackaging/hello.txt
- Plugins/AWSLambdaPackager/Plugin.swift
This change updates the SwiftPM plugin to include the executable's resources in the archive.
When deploying a Lambda function that generates HTML content I needed a way to package template HTML files along with the executable. Defining the resources in the `Package.swift` and then packaging them in the archive in a way so that Swift can access them using `Bundle.main.resourceURL` felt like the best way to accomplish this.
Example:
```
.executableTarget(
name: "Website",
dependencies: [
.product(name: "AWSLambdaRuntime", package: "swift-aws-lambda-runtime"),
],
resources: [
.process("template.stencil"),
]),
```
Plugin code has been modified to generate a `Contents/Resources` directory inside the final archive which includes the resources defined in the executable's target from …
> Add support for resources when packaging using the SwiftPM plugin

- Sources/AWSLambdaRuntimeCore/DetachedTasks.swift
- Sources/AWSLambdaRuntimeCore/LambdaContext.swift
- Sources/AWSLambdaRuntimeCore/LambdaRunner.swift
- Tests/AWSLambdaRuntimeCoreTests/DetachedTasksTests.swift
- readme.md
Introduces a system that allows to keep the execution environment running after submitting the response for a synchronous invocation.
This is a draft PR, only meant to gather feedbacks. This code requires some polishing and testing.
The lines commented with `// To discuss:` require careful consideration.
It is common for a Lambda function to depend on several other serverless services (SQS, APIGW WebSockets, SNS, EventBridge, X-Ray just to name a few). In many occasions, such services might perform non-critical work like sending a push notification to the user, store metrics or flush a set of spans. In these scenarios, the occurrence of a non-recoverable error usually doesn't mean that the whole invocation should fail and result in a sad 500. At the same time, awaiting for such tasks to …
> [Draft] Detached tasks

- Sources/AWSLambdaRuntimeCore/ControlPlaneRequest.swift
- Sources/AWSLambdaRuntimeCore/LambdaRunner.swift
- Sources/AWSLambdaRuntimeCore/LambdaRuntimeClient.swift
- Sources/AWSLambdaRuntimeCore/LambdaRuntimeClientProtocol.swift
- Tests/AWSLambdaRuntimeCoreTests/ControlPlaneRequestTests.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaRuntimeClientTest.swift
To start implementing the v2 API (#339), we first want to introduce the `LambdaRuntimeClientProtocol`. Objects conforming to this protocol can then be used with `LambdaRuntime`.
- Introduced `LambdaRuntimeClientProtocol` and the associated `LambdaResponseStreamWriter` protocol.
- Renamed the existing `Invocation` struct to `InvocationMetadata` since it does not contain the actual invocation event data itself.
- Added an `Invocation` struct which contains `InvocationMetadata` and `ByteBuffer`.
`LambdaRuntime` can be tested more easily through a mock client conforming to `LambdaRuntimeClientProtocol`.
> Introduce LambdaRuntimeClientProtocol

- Package.swift
The Swift 6.0 Linux nightlies have not contained `swift-testing` yet. We will remove it as soon as it is part of the toolchain.
More context:
https://forums.swift.org/t/an-update-about-swift-testing-in-the-swift-6-toolchain/74075
> Add `swift-testing` dependency

- Tests/AWSLambdaRuntimeCoreTests/LambdaHandlerTest.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaTest.swift
- Tests/AWSLambdaRuntimeCoreTests/MockLambdaServer.swift
- Tests/AWSLambdaRuntimeCoreTests/Utils.swift
For the MockServer we should not use a hardcoded port.
- We want to be able to run unit tests in parallel
- The MockServer can now pick its own port and report the port it picked back to the user.
Tests can run in parallel.
> Don't use hardcoded port for MockServer

- Sources/AWSLambdaRuntime/Lambda+Codable.swift
- Sources/AWSLambdaRuntimeCore/LambdaRuntimeClientProtocol.swift
- Sources/AWSLambdaRuntimeCore/NewLambda+JSON.swift
- Sources/AWSLambdaRuntimeCore/NewLambda.swift
- Sources/AWSLambdaRuntimeCore/NewLambdaContext.swift
- Sources/AWSLambdaRuntimeCore/NewLambdaHandlers.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaMockClient.swift
- Tests/AWSLambdaRuntimeTests/NewLambda+CodableTests.swift
As part of the implementation of the v2 API (#339), we want to add the handler protocols `LambdaHandler` and `LambdaWithBackgroundProcessingHandler`.
- Added the two remaining handler protocols: `LambdaHandler` and `LambdaWithBackgroundProcessingHandler`.
- Note: `LambdaHandler` is currently temporarily named as `NewLambdaHandler` as there is already an existing `LambdaHandler`. This will be sorted out closer to release.
- Added `LambdaHandlerAdapter` and `LambdaCodableAdapter` to allow the two new handler protocols to work with the `LambdaRuntime` (as `LambdaRuntime` requires a `StreamingLambdaHandler` conforming handler).
- `LambdaHandlerAdapter`:
- Adapts a `LambdaHandler` conforming handler to conform to `LambdaWithBackgroundProcessingHandler` by passing the output returned from …
> Add new handler protocols + Codable support

- Package.swift
We can depend on `NIOCore` and `NIOPosix` instead of `NIO` to reduce package size.
- Removed `NIO` and instead added `NIOCore` and `NIOPosix` in `Package.swift`.
Reduced package size.
> Depend on NIOCore and NIOPosix instead of NIO

- Plugins/AWSLambdaPackager/Plugin.swift
add a `--help` option to the archiver plugin 
The only way to know what available options are was to look at the code 
Add a `swift package archive --help` command line option to print a descriptive help text 
```
$ swift package archive --help                                 
OVERVIEW: A SwiftPM plugin to build and package your lambda function.
REQUIREMENTS: To use this plugin, you must have docker installed and started.
USAGE: swift package --disable-sandbox archive [--help] [--verbose]
[--output-directory <path>]
[--products <list of products>]
[--configuration debug | release]
[--swift-version <version>]
[--base-docker-image <docker_image_name>]
[--disable-docker-image-update]
OPTIONS:
--verbose                     Produce verbose output for debugging.
--output-directory <path> …
```
> add help option on archiver plugin

- Plugins/AWSLambdaPackager/Plugin.swift
Fixes #378.
We love fast startups.
- We name our executable bootstrap now. This means we don't need to create a symlink that links to our actual executable. This should improve cold starts.
Faster startups.
> Name executable bootstrap, don't create symlink

- Examples/APIGateway/README.md
- Examples/HelloWorld/README.md
- Package.swift
- Plugins/AWSLambdaPackager/Plugin.swift
- Sources/AWSLambdaRuntimeCore/Documentation.docc/Resources/code/04-01-02-plugin-archive.sh
- Sources/AWSLambdaRuntimeCore/Documentation.docc/Resources/code/04-01-03-plugin-archive.sh
- Sources/AWSLambdaRuntimeCore/Documentation.docc/Resources/code/04-01-04-plugin-archive.sh
- Sources/AWSLambdaRuntimeCore/Documentation.docc/quick-setup.md
- readme.md
removes the need to `--disable-sandbox` and update docs and examples
> add docker fine grained permission to the plugin

- .github/workflows/pull_request.yml
- Plugins/AWSLambdaPackager/PluginUtils.swift
- Sources/AWSLambdaRuntime/Lambda+Codable.swift
- Sources/AWSLambdaRuntimeCore/Lambda+Codable.swift
- Sources/AWSLambdaRuntimeCore/LambdaHandlers.swift
Use this PR to make most CI green again.
> Fix docs CI

- Package.swift
We should land #392 first and then rebase on top of it.
> Remove swift-testing package dependency

- Sources/AWSLambdaRuntimeCore/LambdaRuntime.swift
We should land #392 first and then rebase.
> Use Mutex instead of NIOLockedValueBox

- .github/workflows/pull_request.yml
Recently added python linter in swiftlang/github-workflows causes the CI to break.
We don't use python in this project, I'm disabling it
> Do not run python linter during CI

- .github/workflows/pull_request.yml
Align to the new version of the CI script is Swift NIO project https://github.com/apple/swift-nio/commit/c16420c4a7e026174e4eb373953a8eae41a7a4a8
> [CI] drop Swift 5.8

- .github/workflows/pull_request.yml
Musl allows to create self-contained binary that do not required any linux library 
This is a promising path forward for the runtime as it would allow to reduce the binary dependencies on the OS managed by Lambda (think about a migration from Amazon Linux 2 to Amazon Linux 2023) 
While, there will probably have an impact of startup times due to larger binary, musl should be a packaging option for developers that want to use it.
> [CI] add testing on musl

- .github/workflows/pull_request.yml
- Sources/AWSLambdaRuntimeCore/LambdaRuntime.swift
Set the log level to LOG_LEVEL env variable
LOG_LEVEL environment variable was not used
I made the following changes to `LambdaRuntime` 
- transform `log` from `let` to `var` (I hope it does not impact Swift 6 language mode) 
- Set the logger logLevel to the value of the ENV varaibale, defaulting to `.info` when the value is incorrect or not set 
By setting the log level at the creation of the runtime, before entering in the loop, I know that a change of the value in the Lambda console will not affect running microVM. Only microVM launched after the change will pick up the new value, which will eventually affect all containers as the Lambda service replaces microVM on a regular basis.
The alternative is to set the log level before each invocation of the user-provided handler.  This …
> Set the log level to LOG_LEVEL env variable

- Sources/AWSLambdaRuntime/Docs.docc/index.md
- readme.md
add an additional section to the README
> add summary + link to API design doc in the readme

- readme.md
_[Explain here the context, and why you're making that change. What is the problem you're trying to solve.]_
_[Describe the modifications you've done.]_
_[After your change, what will change.]_
> formatting

- .github/workflows/pull_request.yml
- Examples/BackgroundTasks/.gitignore
- Examples/BackgroundTasks/Package.swift
- Examples/BackgroundTasks/README.md
- Examples/BackgroundTasks/Sources/main.swift
- Sources/AWSLambdaRuntime/Lambda+Codable.swift
- readme.md
Add code example for Lambda Background Tasls 
Partially addresses https://github.com/swift-server/swift-aws-lambda-runtime/issues/376
Add a directory `Examples/BackgroundTasks` with code sample and a README
I also slightly modified `Lambda+Codable.swift` to provide default `JSONEncoder()` and `JSONDecoder()` to not require user to create their own if they don't need to.
Developers know how to use Lambda background tasks
> Add an example and README for background tasks

- .github/workflows/pull_request.yml
- .gitignore
- Examples/HelloJSON/.gitignore
- Examples/HelloJSON/Package.swift
- Examples/HelloJSON/README.md
- Examples/HelloJSON/Sources/main.swift
- Examples/README.md
- Plugins/AWSLambdaPackager/Plugin.swift
- Plugins/AWSLambdaPackager/PluginUtils.swift
- Sources/AWSLambdaRuntimeCore/Lambda+LocalServer.swift
- readme.md
Add a simple JSON input/output example + reference it in the main readme.
I also restructured the main readme to follow the structure that was in V1
I commented out LambdaRuntime+Localserver.swift as it is unused at the moment and causes the CI to fail
> add HelloJSON example + README

- Sources/AWSLambdaRuntimeCore/Lambda+LocalServer.swift
- Sources/AWSLambdaRuntimeCore/LambdaRuntime.swift
- readme.md
The local server code is the one from v1. 
It is not passing Swift 6 CI test but we decided to let the code as is and re-enable the local testing feature first to optimize the developer experience.
We will fix `LambdaRuntime+LocalServer.swift` for Swift 6 in a second phase
This PR fixes https://github.com/swift-server/swift-aws-lambda-runtime/issues/369
> re-enable local testing

- .github/workflows/integration_tests.yml
- Package.swift
- Sources/AWSLambdaRuntimeCore/Lambda+LocalServer.swift
- Sources/AWSLambdaRuntimeCore/LambdaRuntime.swift
Minor changes to the local http server to conform to Swift 6 concurrency.
Suggestions provided by @weissi - thank you !
> Update local server for Swift 6 compliance

- .devcontainer/devcontainer.json
- .gitignore
Adds default devcontainer configuration from SSWG: https://github.com/swift-server/swift-devcontainer-template
Developing for linux can be challenging on macOS because some APIs are not available on linux. By using VSCode and devcontainer you can essentially develop "on linux".
Adds devcontainer config.
When working in VSCode, you can now easily open the project inside a devcontainer.
> Adds default devcontainer configuration

- Sources/AWSLambdaRuntimeCore/LambdaRuntime.swift
> Ensure LOG_LEVEL is correctly picked up

- Examples/BackgroundTasks/Sources/main.swift
- Sources/AWSLambdaRuntime/Context+Foundation.swift
- Sources/AWSLambdaRuntime/Vendored/ByteBuffer-foundation.swift
- Sources/AWSLambdaRuntimeCore/LambdaRuntime.swift
- Sources/MockServer/main.swift
- Tests/AWSLambdaRuntimeCoreTests/InvocationTests.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaMockClient.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaRequestIDTests.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaRunLoopTests.swift
- Tests/AWSLambdaRuntimeCoreTests/MockLambdaServer.swift
- Tests/AWSLambdaRuntimeCoreTests/Utils.swift
- readme.md
We want that the runtime only depends on `FoundationEssentials` where available (ie. on linux) to ensure small binary size. 
Smaller binary size is good for lambda deployment and cold-start times. The runtime should only depend on `FoundationEssentials`.
- replace `import Foundation` with `import FoundationEssentials` if `FoundationEssentials` is available.
- I also applied the same treatment to tests to ensure that catch error where tests run on linux and we use API that is only available in `Foundation` which easily happens when you develop on macOS (where always full `Foundation` is available).
This should allow builds without linking full `Foundation`.
> Explicitly only use `FoundationEssentials` where possible

- Examples/APIGateway/Package.swift
- Examples/BackgroundTasks/Package.swift
- Examples/CDK/Package.swift
- Examples/HelloWorld/Package.swift
- Examples/Streaming/Package.swift
- Sources/AWSLambdaRuntimeCore/Documentation.docc/Resources/code/03-02-05-package.swift
All the `Package.swift` files from the examples use `path: "."` instead of `path: "Sources"` which triggers error messages when users add a `Test` directory.
> [examples] Fix path settings in the examples' Package.swift

- Sources/AWSLambdaRuntimeCore/Documentation.docc/quick-setup.md
Update the quick-setup.md docc file to reflect the Runtime v2 API
> [doc] update quicksetup guide for v2

- Sources/AWSLambdaRuntimeCore/Documentation.docc/Deployment.md
Add a note in the deployment guide to inform Linux user they must have correct permissions to use docker on their system.
Build instructions fail on a fresh Ubuntu installation. See this error report.
https://github.com/swift-server/swift-aws-lambda-runtime/issues/449
Add a note in the deployment guide that Linux user must add their user in the `docker` group.
Hopefully, Linux users will not experience error at first use of `swift package archive`
> [doc] update deployment guide

- .github/workflows/pull_request.yml
- Examples/APIGateway+LambdaAuthorizer/.gitignore
- Examples/APIGateway+LambdaAuthorizer/Package.swift
- Examples/APIGateway+LambdaAuthorizer/README.md
- Examples/APIGateway+LambdaAuthorizer/Sources/APIGatewayLambda/main.swift
- Examples/APIGateway+LambdaAuthorizer/Sources/AuthorizerLambda/main.swift
- Examples/APIGateway+LambdaAuthorizer/template.yaml
- Examples/README.md
Add an example of an APIGateway Lambda Authorizer
Lambda Authorizers allow developers to write custom logic to validate HTTP REST requests.
This example shows how to write a Lambda Authorizer in Swift and how to configure an API Gateway to use a Lambda Authorizer.
This example use a SAM template to deploy the resources.
- Add `Examples/APIGateway+LambdaAuthorizer` directory with the source code, a `template.yaml`, and a `README` file.
- Add a reference to the new example in `Examples/README`
- Modify CI to build the new example 
There is a new example showing how to develop a Lambda authorizer in Swift and how to attach it to an APIGateway with SAM
> [examples]  Add an example of an APIGateway Lambda Authorizer

- readme.md
Update readme to add a link to IAM create role function
> add link to IAM create role function

- .github/workflows/integration_tests.yml
- .github/workflows/pull_request.yml
- .github/workflows/scripts/check-archive-plugin.sh
- .licenseignore
- Examples/ResourcesPackaging/.gitignore
- Examples/ResourcesPackaging/Package.swift
- Examples/ResourcesPackaging/Sources/main.swift
- Examples/ResourcesPackaging/hello.txt
- Plugins/AWSLambdaPackager/Plugin.swift
- scripts/test-plugin-ubuntu.sh
- scripts/ubuntu-install-swift.sh
- scripts/ubuntu-test-plugin.sh
When including resources in the package and packaging on Ubuntu, `FileManager` throws a FilePermission error. The docker daemon runs as root and files to be copied are owned by `root` while the archiver runs as the current user (`ubuntu`  on EC2 Ubuntu). The `FileManager` manages to copy the files but throws an error after the copy. We suspect the `FileManager` to perform some kind of operation after the copy and it fails because of the `root` permission of the files. 
See https://github.com/swift-server/swift-aws-lambda-runtime/issues/449#issuecomment-2595978246 for a description of the problem.
This PR contains code to reproduce the problem, a very simple workaround, and an integration test.
The workaround consists of 
- trapping all errors
- verify if the error is the permission error …
> [plugin] support for resources packaging on ubuntu

- Examples/HelloWorld/README.md
The local testing instruction are missing from the hello world example.  The format of the payload is not intuitive or trivial to guess. We need to make it explicit
> add local testing instructions to hello world example

- Examples/APIGateway+LambdaAuthorizer/Package.swift
- Examples/APIGateway/Package.swift
- Examples/CDK/Package.swift
- Examples/S3_AWSSDK/Package.swift
- Examples/S3_Soto/Package.swift
- Examples/Testing/Package.swift
Now that the swift Lambda event library has been tagged 1.0.0, update all the examples to use `from: "1.0.0"` instead of `main` branch
> [examples] Update to Swift Lambda Events 1.0.0

- .github/workflows/pull_request.yml
- Examples/README.md
- Examples/S3EventNotifier/.gitignore
- Examples/S3EventNotifier/Package.swift
- Examples/S3EventNotifier/README.md
- Examples/S3EventNotifier/Sources/main.swift
Add `S3EventNotifier` example
There is currently no example regarding an AWS event triggered lambda, such as a lambda that gets invoked on an S3 object upload. I've had to look for a while to figure out that the `AWSLambdaEvents` exists and that it can be used for that (had to find out via a Java example! 😜) so I think this could be useful and a somewhat common use case
Added an example of a lambda that gets triggered when an object gets uploaded to an S3 bucket.
I have not described how to set up the actual S3 event in AWS because I figured if you needed such a lambda you'd know, but I can describe that too in the README if needed
> Add `S3EventNotifier` example

- Package.swift
- Sources/AWSLambdaRuntime/Lambda+Codable.swift
- Sources/AWSLambdaRuntimeCore/Lambda+Codable.swift
- Sources/AWSLambdaRuntimeCore/Lambda+LocalServer.swift
- Sources/AWSLambdaRuntimeCore/LambdaHandlers.swift
- Sources/AWSLambdaRuntimeCore/LambdaRuntimeClient.swift
This is a huge step into being 100% sendable safe in Lambda!
> Enable Swift 6 mode!

- Package.swift
Update swift-nio to 2.81.0 to fix Swift 6 errors
> Using swift-nio 2.81.0

- Sources/AWSLambdaRuntimeCore/Lambda.swift
- Sources/AWSLambdaRuntimeCore/LambdaRuntimeClient.swift
- Tests/AWSLambdaRuntimeCoreTests/LambdaRuntimeClientTests.swift
Allow `LambdaChannelHandler.nextInvocation` to be cancelled.
If we want to use ServiceLifecycle with the lambda runtime the lambda runtime needs to be cancellable either via a ServiceLifecycle graceful shutdown or via Task cancellation. To avoid bringing in the ServiceLifecycle dependency this PR adds cancellation via Task cancellation handler.
Add `withTaskCancellationHandler` to nextInvocation which calls close on cancel. 
In `LambdaChannelHandler.channelInactive` resume continuation if state is `waitingForNextInvocation`
Added `LambdaRuntimeClientTests.testCancellation`
You can now cancel the runtime while it is waiting for the next invocation.
> [core] Add cancellation handling for nextInvocation()

- Sources/AWSLambdaRuntime/ControlPlaneRequestEncoder.swift
- Sources/AWSLambdaRuntime/LambdaRuntimeClient.swift
- Tests/AWSLambdaRuntimeCoreTests/ControlPlaneRequestEncoderTests.swift
The user-agent string was repeated at 5+ different places in the source code.
I defined it as a constant in the `ControlPlaneRequest` struct where other similar constant have been defined and make sure the rest of the code only uses that constant.
This should address https://github.com/swift-server/swift-aws-lambda-runtime/issues/492
> declare user agent string only once

- .github/workflows/pull_request.yml
~~Attempt to fix CI~~
Remove usage of deprecated parameters on unit-test. 
- explicitly enable tests on nightly 6.0
- explicitly enable tests on nightly next
- explicitly enable tests on nightly main
At the time of this writing, this resolves to 
```
linux_6_0_container_image="swift:6.0-jammy"
linux_nightly_next_container_image="swiftlang/swift:nightly-6.1-jammy"
linux_nightly_main_container_image="swiftlang/swift:nightly-main-jammy"
```
> [ci] : Remove deprecated options on unit-test action

- Sources/AWSLambdaRuntime/ControlPlaneRequest.swift
- Sources/AWSLambdaRuntime/Lambda+LocalServer.swift
- Sources/AWSLambdaRuntime/Lambda.swift
- Sources/AWSLambdaRuntime/LambdaContext.swift
- Sources/AWSLambdaRuntime/LambdaRuntime.swift
- Sources/AWSLambdaRuntime/LambdaRuntimeClient.swift
- Sources/AWSLambdaRuntime/LambdaRuntimeClientProtocol.swift
- Sources/AWSLambdaRuntime/LambdaRuntimeError.swift
- Sources/AWSLambdaRuntime/Utils.swift
Allow the compiler to specialize more code by applying `@inlinable` to generic code.
> Add inlinable where potentially usefull

- .github/workflows/pull_request.yml
Reverts swift-server/swift-aws-lambda-runtime#510
I think the issue https://github.com/swift-server/swift-aws-lambda-runtime/issues/509 that caused this tests disabling has been resolved in Swift and would like to confirm here as well.
> Revert "[ci] : Remove deprecated options on unit-test action"

- .gitignore
- Tests/AWSLambdaRuntimeTests/ControlPlaneRequestEncoderTests.swift
- Tests/AWSLambdaRuntimeTests/LambdaRuntimeClientTests.swift
- Tests/AWSLambdaRuntimeTests/MockLambdaServer.swift
- Tests/AWSLambdaRuntimeTests/UtilsTest.swift
- scripts/check-format-linux.sh
- scripts/check-format.sh
Remove dependency on XCTest
As 6.1 does not include XCTest anymore, finish the migration to Swift testing 
Replace XCTest by Swift Testing in two files
`swift test` works on 6.1.2
> Remove dependency on XCTest

- Sources/AWSLambdaRuntime/LambdaHandlers.swift
- Sources/AWSLambdaRuntime/SendableMetatype.swift
Add SendableMetatype conformance to StreamingLambdaHandler
Swift 6.2 introduced new protocol SendableMetatype for Types that are Sendable 
Added `_Lambda_SendableMetatype` typealias for SendableMetatype in Swift 6.2
and 
```swift
public protocol StreamingLambdaHandler: _Lambda_SendableMetatype {
```
No more compile warnings
> Add SendableMetatype conformance

- Sources/AWSLambdaRuntime/Lambda+LocalServer.swift
- Sources/AWSLambdaRuntime/LambdaRuntime+ServiceLifecycle.swift
- Sources/AWSLambdaRuntime/LambdaRuntime.swift
- Tests/AWSLambdaRuntimeTests/LambdaRuntimeClientTests.swift
- Add ServiceLifecycle version of `LambdaRuntime.run` that wraps internal `_run` call in `cancelOnGracefulShutdown`
- Add cancellation handlers for shutting down existing connections in Local lambda
- Added test for lambda graceful shutdown
Ensure local lambda supports graceful shutdown
> Add support for local server graceful shutdown

- Sources/AWSLambdaRuntime/Lambda+LocalServer.swift
- Tests/AWSLambdaRuntimeTests/Lambda+CodableTests.swift
- Tests/AWSLambdaRuntimeTests/LambdaRunLoopTests.swift
- Tests/AWSLambdaRuntimeTests/LambdaRuntimeTests.swift
- Tests/AWSLambdaRuntimeTests/MockLambdaClient.swift
tiny syntax changes in the test suite
> [tests] minor changes, mostly syntaxic

- Sources/AWSLambdaRuntime/ControlPlaneRequestEncoder.swift
- Sources/AWSLambdaRuntime/Version.swift
Add a hard coded version number to the user agent string, for an eventual identification by the Lambda service
It's [an issue](https://github.com/swift-server/swift-aws-lambda-runtime/issues/108) that was open more than 5 years ago and was never addressed.  At the time, the consensus was to pickup a version number for the Package.swift file and the maintainer at the time decided to wait for Swift to implement this.
Five years later, and several major version of Swift later, this is still not available. I decided to move on and implement a less optimal solution. This can be replaced in the future if package version ever becomes part of Package.swift.
Add a version enum to isolate the versioning in one place. I decided to keep it simple and not over engineering it with major, minor, patch …
> fix: [core] Hard code version number in user agent string (#98)

- Sources/AWSLambdaRuntime/LambdaRuntime.swift
- Sources/AWSLambdaRuntime/LambdaRuntimeError.swift
- Tests/AWSLambdaRuntimeTests/LambdaRuntime+ServiceLifeCycle.swift
- Tests/AWSLambdaRuntimeTests/LambdaRuntimeClientTests.swift
- Tests/AWSLambdaRuntimeTests/LambdaRuntimeTests.swift
- Tests/AWSLambdaRuntimeTests/PoolTests.swift
- Add a test on `LambdaRuntime` for cancellable.
- Move the service life cycle test to its own file
> [test] Add a test for cancellable

- Sources/AWSLambdaRuntime/Lambda.swift
Add a log statement in the Lambda loop, before calling the user's handler to show the raw payload before any attempt to decode it.
This was available in Runtime v1 and is now ported to v2.
This fixes https://github.com/swift-server/swift-aws-lambda-runtime/issues/404
This is useful when handling custom event and there is a Decoding error. It allows to see the exact payload received by the handler before any attempt to decode it.
Add a log.trace statement with metatadata. Metadata are computed only when the log level is trace or below. 
```
2025-07-21T08:58:33+0200 trace LambdaRuntime : Event's first bytes={"name": "me", "age": 50} aws-request-id=769127502334125 [AWSLambdaRuntime] sending invocation event to lambda handler
```
> fix [core] trace level shows the first kb of the payload before being decoded

- Examples/Streaming/README.md
- Sources/AWSLambdaRuntime/Lambda+LocalServer.swift
The local server used for testing functions locally (`swift run`) now support streaming lambda functions
Fix https://github.com/swift-server/swift-aws-lambda-runtime/issues/528
> [core] Add support for streaming function to the local server

- Examples/APIGateway+LambdaAuthorizer/Package.swift
- Examples/APIGateway/Package.swift
- Examples/BackgroundTasks/Package.swift
- Examples/CDK/Package.swift
- Examples/HelloJSON/Package.swift
- Examples/HelloWorld/Package.swift
- Examples/ResourcesPackaging/Package.swift
- Examples/S3EventNotifier/Package.swift
- Examples/S3_AWSSDK/Package.swift
- Examples/S3_Soto/Package.swift
- Examples/ServiceLifecycle+Postgres/Package.swift
- Examples/Streaming/Package.swift
- Examples/StreamingFromEvent/Package.swift
- Examples/Testing/Package.swift
- Examples/Tutorial/Package.swift
- Examples/_MyFirstFunction/create_and_deploy_function.sh
- Sources/AWSLambdaRuntime/Docs.docc/Resources/code/03-02-03-package.swift
- Sources/AWSLambdaRuntime/Docs.docc/Resources/code/03-02-04-package.swift
- Sources/AWSLambdaRuntime/Docs.docc/Resources/code/03-02-05-package.swift
- Sources/AWSLambdaRuntime/Docs.docc/quick-setup.md
- readme.md
Change dependencies in `Examples/*` and documentation to `from: "2.0.0-beta.1"`
> prepare 2.0.0-beta.1

- readme.md
When reading about the V2 changes , I noticed that the link for Response Streaming in the AWS docs was leading to a 404.
A trailing `]` character was the reason - this PR fixes it.
> Fix link (Response Streaming) in readme.md

- Package.swift
- Package@swift-6.0.swift
- Tests/AWSLambdaRuntimeTests/LambdaLocalServerTests.swift
See title. ServiceLifecycle sadly requires 10.15.
> Allow compiling on macOS

- Examples/APIGatewayV1/Package.swift
- Examples/APIGatewayV1/README.md
- Examples/APIGatewayV1/Sources/main.swift
- Examples/APIGatewayV1/template.yaml
This PR adds an APIGateway V1 example, which differs slightly from the existing [V2 example](https://github.com/swift-server/swift-aws-lambda-runtime/tree/main/Examples/APIGateway).
While APIGatewayV2 has existed for a while, there are still some scenarios where V1 is preferable (see [Choose between REST APIs and HTTP APIs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-vs-rest.html) for more details). This PR adds a working example for the `Api` endpoint type.
Sources/main.swift
- Swapped APIGatewayRequestV2 and APIGatewayResponseV2 for their unversioned counterparts (aka V1).
template.yaml
- Changed the Events name and corresponding `Type: Api` values.
- Added necessary additional properties to define a `GET` endpoint for an `Api` endpoint.
Readme.md
- Updated the …
> [Example] Add APIGatewayV1 example
